const WORD_BANK = {
  "Animals": [
    "TIGER", "LION", "ELEPHANT", "GIRAFFE", "DOLPHIN",
    "PENGUIN", "KANGAROO", "MONKEY", "PANDA", "RABBIT",
    "CAT", "DOG", "HORSE", "EAGLE", "SHARK", "OCTOPUS",
    "CHEETAH", "ZEBRA", "GORILLA", "KOALA", "HIPPOPOTAMUS",
    "RHINOCEROS", "CROCODILE", "ALLIGATOR", "WOLF", "FOX",
    "BEAR", "POLAR BEAR", "LEOPARD", "JAGUAR", "CHIMPANZEE",
    "FLAMINGO", "PEACOCK", "OWL", "PARROT", "HAWK",
    "FALCON", "PELICAN", "SEAGULL", "SWAN", "OSTRICH",
    "WHALE", "KILLER WHALE", "SEAL", "SEA LION", "WALRUS",
    "OTTER", "BEAVER", "PLATYPUS", "HEDGEHOG", "SQUIRREL",
    "RACCOON", "BADGER", "DEER", "MOOSE", "CAMEL",
    "LLAMA", "BUFFALO", "HYENA", "MEERKAT", "SLOTH",
    "ARMADILLO", "CHAMELEON", "IGUANA", "GECKO", "TORTOISE",
    "FROG", "SALAMANDER", "JELLYFISH", "STARFISH", "LOBSTER",
    "CRAB", "SEAHORSE", "STINGRAY", "EEL", "PIRANHA",
    "HAMSTER", "GUINEA PIG", "LEMUR", "ORANGUTAN", "BABOON",
    "PUMA", "LYNX", "BOBCAT", "ANTELOPE", "GAZELLE",
    "WARTHOG", "PORCUPINE", "SKUNK", "FERRET", "MONGOOSE"
  ],
  "Food & Drinks": [
    "PIZZA", "BURGER", "SUSHI", "PASTA", "CHOCOLATE",
    "COFFEE", "APPLE", "BANANA", "ICE CREAM", "TACO",
    "SALAD", "CHEESE", "BREAD", "CAKE", "PANCAKE", "HONEY",
    "SANDWICH", "HOT DOG", "FRENCH FRIES", "STEAK", "LASAGNA",
    "BURRITO", "RAMEN", "NOODLES", "DUMPLING", "CROISSANT",
    "BAGEL", "DONUT", "WAFFLE", "MUFFIN", "COOKIE",
    "BROWNIE", "POPCORN", "NACHOS", "GUACAMOLE", "HUMMUS",
    "STRAWBERRY", "BLUEBERRY", "WATERMELON", "PINEAPPLE", "MANGO",
    "ORANGE", "GRAPES", "PEACH", "AVOCADO", "TOMATO",
    "POTATO", "ONION", "GARLIC", "MUSHROOM", "BROCCOLI",
    "CARROT", "CORN", "SPINACH", "CUCUMBER", "CHILI",
    "LEMONADE", "ORANGE JUICE", "MILKSHAKE", "SMOOTHIE", "TEA",
    "HOT CHOCOLATE", "ESPRESSO", "CAPPUCCINO", "ICED TEA", "SODA",
    "YOGURT", "BUTTER", "POPSICLE", "CUPCAKE", "CHEESECAKE",
    "OMELET", "PANINI", "QUESADILLA", "CHURROS", "TIRAMISU",
    "APPLE PIE", "CRANBERRY", "RASPBERRY", "COCONUT", "GINGER",
    "LEMON", "LIME", "PEANUT BUTTER", "JELLY", "POUTINE"
  ],
  "Places & Landmarks": [
    "BEACH", "MOUNTAIN", "HOSPITAL", "SCHOOL", "AIRPORT",
    "LIBRARY", "MUSEUM", "PARK", "HOTEL", "CINEMA",
    "RESTAURANT", "STADIUM", "DESERT", "FOREST", "ISLAND", "OFFICE",
    "CASTLE", "PALACE", "LIGHTHOUSE", "AMUSEMENT PARK", "ZOO",
    "AQUARIUM", "THEATER", "CHURCH", "TEMPLE", "MOSQUE",
    "PYRAMID", "EIFFEL TOWER", "STATUE OF LIBERTY", "COLOSSEUM", "BIG BEN",
    "TAJ MAHAL", "GREAT WALL", "GRAND CANYON", "NIAGARA FALLS", "VOLCANO",
    "CAVE", "WATERFALL", "VALLEY", "CANYON", "GLACIER",
    "HARBOR", "BRIDGE", "TUNNEL", "SUBWAY STATION", "TRAIN STATION",
    "SUPERMARKET", "BAKERY", "PHARMACY", "POLICE STATION", "FIRE STATION",
    "UNIVERSITY", "CAMPUS", "LABORATORY", "GYM", "CASINO",
    "SKATE PARK", "BOWLING ALLEY", "WATER PARK", "SPA", "RESORT",
    "PENTHOUSE", "CABIN", "COTTAGE", "MANSION", "BARN",
    "OBSERVATORY", "PLANETARIUM", "OPERA HOUSE", "CLOCK TOWER", "FOUNTAIN",
    "MARKETPLACE", "COURTHOUSE", "POST OFFICE", "CITY HALL", "EMBASSY"
  ],
  "Objects & Items": [
    "PHONE", "CAMERA", "GUITAR", "BICYCLE", "WATCH",
    "CHAIR", "TABLE", "KEY", "BOOK", "MIRROR",
    "CLOCK", "BOTTLE", "UMBRELLA", "GLASSES", "WALLET", "BACKPACK",
    "HEADPHONES", "LAPTOP", "TELEVISION", "MICROWAVE", "REFRIGERATOR",
    "TOASTER", "BLENDER", "VACUUM CLEANER", "LAMP", "FLASHLIGHT",
    "SCISSORS", "HAMMER", "SCREWDRIVER", "WRENCH", "TAPE MEASURE",
    "COMPASS", "TELESCOPE", "MICROSCOPE", "BINOCULARS", "MAGNIFYING GLASS",
    "SUITCASE", "BRIEFCASE", "PURSE", "PASSPORT", "NOTEBOOK",
    "CALENDAR", "GLOBE", "MAP", "THERMOMETER", "SCALE",
    "VIOLIN", "DRUMS", "PIANO", "TRUMPET", "FLUTE",
    "BALLOON", "KITE", "FRISBEE", "YO YO", "SKATEBOARD",
    "CANDLE", "MATCHBOX", "LIGHTER", "VASE", "PICTURE FRAME",
    "THERMOS", "PADLOCK", "LANTERN", "HOURGLASS", "ALARM CLOCK",
    "PENCIL SHARPENER", "STAPLER", "CLIPBOARD", "PIGGY BANK", "TROPHY"
  ],
  "Activities & Hobbies": [
    "RUNNING", "SWIMMING", "COOKING", "READING", "DANCING",
    "SINGING", "PAINTING", "TRAVELING", "SHOPPING", "SLEEPING",
    "FISHING", "CAMPING", "GARDENING", "WRITING", "DRIVING", "HIKING",
    "SURFING", "SKIING", "SNOWBOARDING", "SKATING", "CYCLING",
    "JOGGING", "MEDITATION", "YOGA", "BAKING", "KNITTING",
    "SEWING", "POTTERY", "PHOTOGRAPHY", "CHESS", "VIDEO GAMING",
    "MAGIC TRICKS", "ASTRONOMY", "BIRDWATCHING", "ROCK CLIMBING", "SCUBA DIVING",
    "SKYDIVING", "BUNGEE JUMPING", "KAYAKING", "CANOEING", "SAILING",
    "HORSEBACK RIDING", "ARCHERY", "BOWLING", "KARAOKE", "ACTING",
    "STAND UP COMEDY", "JOURNALING", "ORIGAMI", "WOODWORKING", "PUZZLE SOLVING",
    "CALLIGRAPHY", "GARDENING", "BOARD GAMING", "WEIGHTLIFTING", "SNORKELING",
    "ICE SKATING", "ROLLERBLADING", "SOLVING CROSSWORDS", "COMPOSTING", "FENCING"
  ],
  "Movies & Characters": [
    "AVATAR", "TITANIC", "INCEPTION", "GLADIATOR", "JAWS",
    "FROZEN", "MATRIX", "BATMAN", "SUPERMAN", "TARZAN",
    "SHREK", "ALADDIN", "DRACULA", "JURASSIC PARK", "COCO", "AMELIE",
    "STAR WARS", "HARRY POTTER", "LORD OF THE RINGS", "SPIDERMAN", "IRON MAN",
    "THOR", "HULK", "CAPTAIN AMERICA", "BLACK PANTHER", "WOLVERINE",
    "DEADPOOL", "JOKER", "SHERLOCK HOLMES", "JAMES BOND", "INDIANA JONES",
    "PIRATES OF THE CARIBBEAN", "FINDING NEMO", "TOY STORY", "LION KING", "CINDERELLA",
    "PINOCCHIO", "PETER PAN", "FRANKENSTEIN", "GODZILLA", "KING KONG",
    "TRANSFORMERS", "TERMINATOR", "BACK TO THE FUTURE", "GHOSTBUSTERS", "THE GODFATHER",
    "WALL E", "RATATOUILLE", "UP", "INTERSTELLAR", "MAD MAX",
    "MONSTERS INC", "CARS", "HERCULES", "MULAN", "BRAVE"
  ],
  "Sports & Games": [
    "CRICKET", "FOOTBALL", "BASKETBALL", "TENNIS", "GOLF",
    "BOXING", "CHESS", "VOLLEYBALL", "BASEBALL", "RUGBY",
    "BADMINTON", "HOCKEY", "SURFING", "SKIING", "BOWLING", "KARATE",
    "TABLE TENNIS", "BILLIARDS", "SNOOKER", "DARTS", "ARCHERY",
    "FENCING", "WRESTLING", "JUDO", "TAEKWONDO", "GYMNASTICS",
    "SWIMMING", "DIVING", "WATER POLO", "ROWING", "HANDBALL",
    "ICE HOCKEY", "CURLING", "BOBSLEIGH", "FIGURE SKATING", "SNOWBOARDING",
    "SKATEBOARDING", "MOTOR RACING", "FORMULA ONE", "TRIATHLON", "MARATHON",
    "POKER", "MONOPOLY", "SCRABBLE", "DOMINOES", "CHECKERS",
    "LACROSSE", "POLO", "SQUASH", "KICKBOXING", "SUMO WRESTLING",
    "DISC GOLF", "CANOE SLALOM", "LUGE", "PADDLEBOARDING", "CRICKET"
  ],
  "Nature & Elements": [
    "RAIN", "SNOW", "SUN", "MOON", "RIVER",
    "OCEAN", "STAR", "CLOUD", "WIND", "FLOWER",
    "TREE", "FIRE", "VOLCANO", "LIGHTNING", "RAINBOW", "LAKE",
    "WATERFALL", "TORNADO", "HURRICANE", "EARTHQUAKE", "TSUNAMI",
    "AVALANCHE", "DESERT", "JUNGLE", "FOREST", "SWAMP",
    "ISLAND", "CANYON", "GLACIER", "GALAXY", "COMET",
    "ASTEROID", "ECLIPSE", "NORTHERN LIGHTS", "SUNRISE", "SUNSET",
    "THUNDER", "HAIL", "FOG", "DEW", "FROST",
    "CORAL REEF", "CAVE", "VALLEY", "MEADOW", "GEYSER",
    "METEOR", "SAND DUNE", "OASIS", "TUNDRA", "COASTLINE",
    "REEF", "LAGOON", "HOT SPRING", "QUICKSAND", "MIST"
  ],
  "Technology & Devices": [
    "LAPTOP", "INTERNET", "ROBOT", "SOFTWARE", "WEBSITE",
    "KEYBOARD", "MOUSE", "SCREEN", "PRINTER", "BATTERY",
    "CHARGER", "HEADPHONES", "ROUTER", "CAMERA", "AI", "GAMEPAD",
    "SMARTPHONE", "TABLET", "SMARTWATCH", "DRONE", "VIRTUAL REALITY",
    "SATELLITE", "SUPERCOMPUTER", "MICROCHIP", "HARD DRIVE", "USB DRIVE",
    "BLUETOOTH", "WIFI", "MICROPHONE", "WEBCAM", "PROJECTOR",
    "SMART SPEAKER", "FITNESS TRACKER", "ELECTRIC CAR", "SOLAR PANEL", "CYBORG",
    "BLOCKCHAIN", "ALGORITHM", "HOLOGRAM", "3D PRINTER", "ROBOTIC ARM",
    "FIREWALL", "SERVER", "CLOUD STORAGE", "ANTENNA", "TOUCHSCREEN",
    "DATABASE", "PODCAST", "STREAMING", "FIBER OPTIC", "SMART BULB"
  ],
  "Everyday Things": [
    "TEACHER", "SHOES", "PENCIL", "PAPER", "COAT",
    "WINDOW", "DOOR", "KEYS", "SOAP", "TOWEL",
    "BED", "PILLOW", "BRUSH", "CUP", "SPOON", "COIN",
    "FORK", "KNIFE", "PLATE", "BOWL", "NAPKIN",
    "TOOTHBRUSH", "TOOTHPASTE", "SHAMPOO", "COMB", "HAIR DRYER",
    "BLANKET", "MATTRESS", "CURTAIN", "RUG", "CARPET",
    "TRASH CAN", "BROOM", "MOP", "BUCKET", "SPONGE",
    "NOTEBOOK", "ERASER", "RULER", "STAPLER", "ENVELOPE",
    "STAMP", "SCISSORS", "GLUE", "PAPERCLIP", "HIGHLIGHTER",
    "BOOKMARK", "DOORKNOB", "LIGHT SWITCH", "WALL CLOCK", "COATHANGER",
    "DUSTPAN", "SAFETY PIN", "RUBBER BAND", "BATHROBE", "SLIPPERS"
  ],
  "Professions & Careers": [
    "DOCTOR", "SURGEON", "NURSE", "DENTIST", "PHARMACIST",
    "ASTRONAUT", "PILOT", "CAPTAIN", "SAILOR", "FIREFIGHTER",
    "POLICE OFFICER", "DETECTIVE", "JUDGE", "LAWYER", "PROFESSOR",
    "SCIENTIST", "ARCHAEOLOGIST", "ENGINEER", "ARCHITECT", "CHEF",
    "BAKER", "FARMER", "GARDENER", "PLUMBER", "ELECTRICIAN",
    "CARPENTER", "MECHANIC", "WELDER", "PHOTOGRAPHER", "JOURNALIST",
    "MUSICIAN", "PAINTER", "SCULPTOR", "ACTOR", "DIRECTOR",
    "MAGICIAN", "LIFEGUARD", "VETERINARIAN", "FLIGHT ATTENDANT", "COACH",
    "LIBRARIAN", "METEOROLOGIST", "ASTRONOMER", "ZOOLOGIST", "PARAMEDIC",
    "BARBER", "TAILOR", "TRANSLATOR", "CHOREOGRAPHER", "ECONOMIST"
  ],
  "Vehicles & Transport": [
    "AIRPLANE", "HELICOPTER", "SUBMARINE", "SPACESHIP", "ROCKET",
    "HOT AIR BALLOON", "TRAIN", "BULLET TRAIN", "SUBWAY", "TRAM",
    "BUS", "SCHOOL BUS", "AMBULANCE", "FIRE TRUCK", "POLICE CAR",
    "TAXI", "MOTORCYCLE", "SCOOTER", "BICYCLE", "SKATEBOARD",
    "ROLLER SKATES", "TRUCK", "VAN", "TRACTOR", "BULLDOZER",
    "EXCAVATOR", "SPEEDBOAT", "YACHT", "CRUISE SHIP", "FERRY",
    "CARGO SHIP", "HOVERCRAFT", "JET SKI", "CANOE", "KAYAK",
    "GONDOLA", "SAILBOAT", "SNOWMOBILE", "GOLF CART", "FORKLIFT",
    "CABLE CAR", "MINIVAN", "MONORAIL", "ROWBOAT", "PADDLEBOAT",
    "STEAMSHIP", "ZEPPELIN", "TROLLEY", "SEGWAY", "RICKSHAW"
  ],
  "Fantasy & Myth": [
    "DRAGON", "UNICORN", "PHOENIX", "WIZARD", "WITCH",
    "SORCERER", "FAIRY", "MERMAID", "VAMPIRE", "WEREWOLF",
    "GHOST", "ZOMBIE", "MUMMY", "GOBLIN", "ELF",
    "DWARF", "GIANT", "TROLL", "OGRE", "CYCLOPS",
    "CENTAUR", "PEGASUS", "GRIFFIN", "KRAKEN", "HYDRA",
    "MINOTAUR", "GARGOYLE", "GENIE", "ALIEN", "SPHINX",
    "MAGIC WAND", "POTION", "CRYSTAL BALL", "FLYING CARPET", "SPELLBOOK",
    "CHIMERA", "BASILISK", "LEPRECHAUN", "VALKYRIE", "BANSHEE",
    "SIREN", "HOBBIT", "GNOME", "POLTERGEIST", "TREANT"
  ],
  "Music & Art": [
    "PIANO", "GUITAR", "VIOLIN", "CELLO", "DRUMS",
    "TRUMPET", "SAXOPHONE", "FLUTE", "CLARINET", "HARP",
    "ACCORDION", "BAGPIPES", "TROMBONE", "HARMONICA", "BANJO",
    "UKULELE", "MICROPHONE", "CONCERT", "SYMPHONY", "OPERA",
    "ORCHESTRA", "CHORUS", "PAINTING", "SCULPTURE", "PORTRAIT",
    "CANVAS", "EASEL", "PALETTE", "GRAFFITI", "MOSAIC",
    "SKETCH", "POTTERY", "ORIGAMI", "CALLIGRAPHY", "GALLERY",
    "TAMBOURINE", "XYLOPHONE", "BASS GUITAR", "SYNTHESIZER", "TRIANGLE",
    "DRUMSTICKS", "METRONOME", "SHEET MUSIC", "ACOUSTIC", "FRESCO"
  ],
  "Clothing & Fashion": [
    "JACKET", "COAT", "SWEATER", "HOODIE", "SHIRT",
    "T-SHIRT", "JEANS", "PANTS", "SHORTS", "SKIRT",
    "DRESS", "SUIT", "TIE", "BOWTIE", "HAT",
    "CAP", "BEANIE", "HELMET", "SCARF", "GLOVES",
    "SOCKS", "SHOES", "SNEAKERS", "BOOTS", "SANDALS",
    "SLIPPERS", "SUNGLASSES", "BELT", "WATCH", "BRACELET",
    "NECKLACE", "RING", "EARRINGS", "BACKPACK", "RAINCOAT",
    "CARDIGAN", "VEST", "OVERALLS", "BLAZER", "TUXEDO",
    "BANDANA", "HEADBAND", "MITTENS", "EARMUFFS", "SUSPENDERS"
  ]
};

// Select a random word ensuring it doesn't match the last few words
function getRandomWord(excludeList = []) {
  const categories = Object.keys(WORD_BANK);
  const randomCategory = categories[Math.floor(Math.random() * categories.length)];
  const words = WORD_BANK[randomCategory];
  
  // Filter out any excluded words
  const availableWords = words.filter(word => !excludeList.includes(word));
  
  if (availableWords.length === 0) {
    // If all words are excluded, fall back to any word from the category
    const fallbackWord = words[Math.floor(Math.random() * words.length)];
    return { category: randomCategory, word: fallbackWord };
  }
  
  const randomWord = availableWords[Math.floor(Math.random() * availableWords.length)];
  return { category: randomCategory, word: randomWord };
}

module.exports = {
  WORD_BANK,
  getRandomWord
};
